### ISSUE TITLE
nk3: firmware update fails

### ISSUE THREAD

**Issue by jmue** [Nitrokey/pynitrokey#153]
The output on my Fedora 35 Workstation is:
```
nitropy nk3 update firmware-nk3xn-lpc55-v1.0.1.sb2 
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM
Current firmware version:  v1.0.0
Updated firmware version:  v1.0.1

Please do not remove the Nitrokey 3 or insert any other Nitrokey 3 devices during the update.
Do you want to perform the firmware update now? [y/N]: Y

Please press the touch button to reboot the device into bootloader mode ...

Traceback (most recent call last):
  File "/home/jens/.local/lib/python3.10/site-packages/spsdk/mboot/interfaces/usb.py", line 152, in open
    self.device.Open(self.path)
  File "/home/jens/.local/lib/python3.10/site-packages/libusbsio/libusbsio.py", line 1322, in Open
    self.logger.info("HID device %d is now open" % self._h)
TypeError: %d format: a real number is required, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jens/.local/bin/nitropy", line 8, in <module>
    sys.exit(nitropy())
  File "/home/jens/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jens/.local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jens/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jens/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jens/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jens/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jens/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/jens/.local/lib/python3.10/site-packages/pynitrokey/cli/nk3/__init__.py", line 241, in update
    with _await_bootloader(ctx) as bootloader:
  File "/home/jens/.local/lib/python3.10/site-packages/pynitrokey/nk3/bootloader.py", line 47, in __enter__
    self.device.open()
  File "/home/jens/.local/lib/python3.10/site-packages/spsdk/mboot/mcuboot.py", line 237, in open
    self._device.open()
  File "/home/jens/.local/lib/python3.10/site-packages/spsdk/mboot/interfaces/usb.py", line 155, in open
    raise McuBootConnectionError(
spsdk.mboot.exceptions.McuBootConnectionError: MBoot: Connection issue -> Unable to open device 'b'/dev/hidraw1'' VID=8352 PID=17117 SN=''
```

**Comment by robin-nitrokey** [comment]
Thanks for the report!  Looks like a permission issue.  Could you please check that you have an entry like this one in your udev rules?

```
# Nitrokey 3 bootloader
SUBSYSTEM=="hidraw", ATTRS{idVendor}=="20a0", ATTRS{idProduct}=="42dd", TAG+="uaccess"
```

**Comment by jmue** [comment]
Sorry no luck, even when added the rule. I suspected a SELinux issue and tried it on Debian Bullseye. But I get similar output. 
```
nitropy nk3 update /home/jens/Downloads/firmware-nk3xn-lpc55-v1.0.1.sb2 
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start, Nitrokey 3 & NetHSM
Current firmware version:  v1.0.0
Updated firmware version:  v1.0.1

Please do not remove the Nitrokey 3 or insert any other Nitrokey 3 devices during the update.
Do you want to perform the firmware update now? [y/N]: Y

Please press the touch button to reboot the device into bootloader mode ...

Traceback (most recent call last):
  File "/home/jens/.local/lib/python3.9/site-packages/spsdk/mboot/interfaces/usb.py", line 152, in open
    self.device.Open(self.path)
  File "/home/jens/.local/lib/python3.9/site-packages/libusbsio/libusbsio.py", line 1322, in Open
    self.logger.info("HID device %d is now open" % self._h)
TypeError: %d format: a number is required, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jens/.local/bin/nitropy", line 8, in <module>
    sys.exit(nitropy())
  File "/home/jens/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jens/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jens/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jens/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jens/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jens/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jens/.local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/jens/.local/lib/python3.9/site-packages/pynitrokey/cli/nk3/__init__.py", line 241, in update
    with _await_bootloader(ctx) as bootloader:
  File "/home/jens/.local/lib/python3.9/site-packages/pynitrokey/nk3/bootloader.py", line 47, in __enter__
    self.device.open()
  File "/home/jens/.local/lib/python3.9/site-packages/spsdk/mboot/mcuboot.py", line 237, in open
    self._device.open()
  File "/home/jens/.local/lib/python3.9/site-packages/spsdk/mboot/interfaces/usb.py", line 155, in open
    raise McuBootConnectionError(
spsdk.mboot.exceptions.McuBootConnectionError: MBoot: Connection issue -> Unable to open device 'b'/dev/hidraw1'' VID=8352 PID=17117 SN=''
```

**Comment by robin-nitrokey** [comment]
Did you reload the udev rules after adding the bootloader rule?  Typically, you need to run something like this:
```
udevadm control --reload-rules && udevadm trigger
```

(Or simply reboot the system …)

**Comment by jmue** [comment]
Yes, I rebooted but also tried "udevadm control --reload"

**Comment by szszszsz** [comment]
> ```
> SUBSYSTEM=="usb", ACTION=="add", ATTRS{idVendor}=="20a0", ATTRS{idProduct}=="42dd",  MODE="0666"
> ```
@robin-nitrokey 
The previous one works for me on Fedora.

@jmue 
Perhaps path is an issue. My rules file is at the following path:
- /usr/local/lib/udev/rules.d/41-nitrokey.rules

Can you check it?

**Comment by robin-nitrokey** [comment]
I accidentally have both rules and it works for me on Debian stable.  I can test tomorrow if both or only one of them work on my system.

**Comment by jmue** [comment]
Adding the default [41-nitrokey.rules](https://raw.githubusercontent.com/Nitrokey/libnitrokey/master/data/41-nitrokey.rules) udev ruleset solved the problem for me on Fedora. Having successfully run the nk3 list, version and test commands with no additional rules, I was unaware of their importance.

**Comment by szszszsz** [comment]
@robin-nitrokey Its probably worth catching this error, and showing a proper guide about Udev rules installing on Linux.
