### ISSUE TITLE
Not pressing the touch button - received CTAP error

### ISSUE THREAD

**Issue by daringer** [Nitrokey/pynitrokey#173]
During `nk3 update` if the touch button is not pressed

```
Please press the touch button to reboot the device into bootloader mode ...
^[[3~
Traceback (most recent call last):
  File "dev/pynitrokey/venv/bin/nitropy", line 8, in <module>
    sys.exit(nitropy())
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/pynitrokey/cli/nk3/__init__.py", line 329, in update
    device.reboot(BootMode.BOOTROM)
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/pynitrokey/nk3/device.py", line 80, in reboot
    self._call(Command.UPDATE)
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/pynitrokey/nk3/device.py", line 106, in _call
    response = self.device.call(command.value)
  File "dev/pynitrokey/venv/lib/python3.10/site-packages/fido2/hid/__init__.py", line 210, in call
    raise CtapError(struct.unpack_from(">B", recv)[0])
fido2.ctap.CtapError: CTAP error: 0x03 - INVALID_LENGTH

```

**Comment by robin-nitrokey** [comment]
So you just let the request time out to reproduce the error?

**Comment by daringer** [comment]
yes, the timeout after `Please press the touch button to reboot the device into bootloader mode ...` is roughly 10secs for me

**Comment by szszszsz** [comment]
Interesting. I think the error should be different on the timeout event here, certainly not CBOR parsing one.

**Comment by robin-nitrokey** [comment]
I have no idea why, but that error is coming from the firmware:

```
            HidCommand::Vendor(UPDATE) => {
                if self.user_present() {
                    if input_data.len() > 0 && input_data[0] == 0x01 {
                        R::reboot_to_firmware_update_destructive();
                    } else {
                        R::reboot_to_firmware_update();
                    }
                } else {
                    return Err(hid::Error::InvalidLength);
                }
            }
```

https://github.com/solokeys/admin-app/blob/99951ba7bc2c577dac1c7a1bb74999eb29e01a34/src/admin.rs#L94
