### ISSUE TITLE
pynitrokey on a fresh install, problem with the latest version reproduced locally with pipx on Ubuntu 22.04:

### ISSUE THREAD

**Issue by rickflowexe** [Nitrokey/pynitrokey#233]
```
root@1fc924ae3e76:/# ~/.local/bin/nitropy 
Traceback (most recent call last):
  File "/root/.local/bin/nitropy", line 5, in <module>
    from pynitrokey.cli import main
  File "/root/.local/pipx/venvs/pynitrokey/lib/python3.10/site-packages/pynitrokey/cli/__init__.py", line 19, in <module>
    import pynitrokey.fido2.operations
  File "/root/.local/pipx/venvs/pynitrokey/lib/python3.10/site-packages/pynitrokey/fido2/__init__.py", line 10, in <module>
    from pynitrokey.fido2.client import NKFido2Client
  File "/root/.local/pipx/venvs/pynitrokey/lib/python3.10/site-packages/pynitrokey/fido2/client.py", line 26, in <module>
    from fido2.ctap1 import CTAP1
ImportError: cannot import name 'CTAP1' from 'fido2.ctap1' (/root/.local/pipx/venvs/pynitrokey/lib/python3.10/site-packages/fido2/ctap1.py)
root@1fc924ae3e76:/# history 
    1  apt update
    2  apt install pipx
    3  pipx install pynitrokey
    7  ~/.local/bin/nitropy 
    ```

**Comment by rickflowexe** [comment]
pynitrokey on a fresh install, problem with the latest version reproduced locally with pipx on Ubuntu 22.04
