### ISSUE TITLE
Windows: no backend available

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#27]
Nitropy cannot view USB devices out of the box. 
Stack trace:
```
PS C:\Windows\system32> nitropy ls
*** ←[31mNitrokey tool for Nitrokey FIDO2 & Nitrokey Start←[39;49;00m
:: 'Nitrokey FIDO2' keys
20873372344B: Nitrokey FIDO2 2.0.0
:: 'Nitrokey Start' keys:
Traceback (most recent call last):
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "nitropy.py", line 3, in <module>
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\click\core.py", line 829, in __call__
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\click\core.py", line 782, in main
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\click\core.py", line 1259, in invoke
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\click\core.py", line 1066, in invoke
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\click\core.py", line 610, in invoke
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\pynitrokey\cli\__init__.py", line 62, in ls
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\pynitrokey\cli\start.py", line 37, in list
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\pynitrokey\start\usb_strings.py", line 46, in get_devices
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\pynitrokey\start\gnuk_token.py", line 637, in gnuk_devices_by_vidpid
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\usb\legacy.py", line 353, in busses
  File "C:\Users\Malli\Desktop\WPy64-3830\python-3.8.3.amd64\lib\site-packages\usb\core.py", line 1263, in find
usb.core.NoBackendError: No backend available
```

**Comment by szszszsz** [comment]
Pasting log after installing libusb:

<details>

<summary>
click to show
</summary>

```
C:\Program Files\pynitrokey>nitropy ls
*** ←[31;01mNitrokey tool for Nitrokey FIDO2 & Nitrokey Start←[39;49;00m
:: 'Nitrokey FIDO2' keys
:: 'Nitrokey Start' keys:
Traceback (most recent call last):
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 40, in run
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 37, in run
  File "nitropy.py", line 3, in <module>
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\click\core.py", line 829, in __call__
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\click\core.py", line 782, in main
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\click\core.py", line 1259, in invoke
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\click\core.py", line 1066, in invoke
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\click\core.py", line 610, in invoke
  File "D:\tools\common\portable_python3_64bit\tmp\pynitrokey-master\pynitrokey\cli\__init__.py", line 60, in ls
  File "D:\tools\common\portable_python3_64bit\tmp\pynitrokey-master\pynitrokey\cli\start.py", line 43, in list
  File "D:\tools\common\portable_python3_64bit\tmp\pynitrokey-master\pynitrokey\start\usb_strings.py", line 46, in get_devices
  File "D:\tools\common\portable_python3_64bit\tmp\pynitrokey-master\pynitrokey\start\gnuk_token.py", line 646, in gnuk_devices_by_vidpid
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\usb\legacy.py", line 354, in <genexpr>
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\usb\legacy.py", line 349, in __init__
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\usb\legacy.py", line 349, in <listcomp>
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\usb\legacy.py", line 335, in __init__
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\usb\legacy.py", line 335, in <listcomp>
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\usb\core.py", line 1128, in __iter__
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\usb\core.py", line 605, in __init__
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\usb\backend\libusb1.py", line 775, in get_configuration_descriptor
  File "D:\tools\common\portable_python3_64bit\python-3.7.0b3.amd64\lib\site-packages\usb\backend\libusb1.py", line 604, in _check
usb.core.USBError: [Errno 2] Entity not found
```

</details>

**Comment by szszszsz** [comment]
@daringer How is the support under Windows working? Could you take a look at the case below?
- https://support.nitrokey.com/t/unable-to-run-nitropy-in-windows-10/2689

**Comment by daringer** [comment]
Haven't verified NK Start with the most recent installer + libusb installed manually. I expect to release 0.4.2 this week with the wine-based build and an included `libusb`, so the problem should vanish entirely

**Comment by daringer** [comment]
well, I am not entirely confident whether this is fun or not :smile: 
but anyways, this is a standalone win32 executable containing the `libusb-1.0.dll` as backend, looks good until now, will do some more testing the next days and hopefully release it with 0.4.2 afterwards:
  
[nitropy-0.4.1.exe.zip](https://github.com/Nitrokey/pynitrokey/files/5435285/nitropy-0.4.1.exe.zip)

Please keep in mind that this is an binary executable (inside the .zip),
you can build your own (similar one as the build is not reproducible) using `build-wine.sh` from the repository

**Comment by daringer** [comment]
update:
looks like there is no party yet, can report that it fails with "usb.core.USBError: [Errno 2] Entity not found" with any possible solution I came up with ...

**Comment by daringer** [comment]
this certainly is *not* fun, digging deeper leads to the following conclusions:
* iteration over `usb.busses()` yields the "Entity not found" error
* using `usb.core.find(find_all=True)` finds the device properly
  * but it looks like communication is not working with the device (basic things like `dev.idProduct` work, but already `dev.langids` is empty, thus no strings can be extracted)
* also interesting is the fact that `pyusb<=1.0.2` cannot even use `usb.core.find()` without crashing with an "access violation" (this at least seems to be a known issue)
* various other operations on the usb-device found via `usb.core.find()` leads to the same "Entity not found" error...

So under the line: `pyusb` seems to work only partly, currently I cannot pinpoint what's wrong here,
**any help is highly appreciated**

**Comment by szszszsz** [comment]
Hi!
1. Could you check if it is working with the Administrator privileges?
2. Getting USB attributes is optional here, as long as we identify the correct device.
3. Here is how hidapi has it's implementation for USB communication for reference: https://github.com/libusb/hidapi/blob/master/windows/hid.c
4. Can we compare our implementation/distribution with some other Python applications which use libusb under Windows?

**Comment by daringer** [comment]
> Hi!
> 
> 1. Could you check if it is working with the Administrator privileges?

:heavy_check_mark: 

> 2. Getting USB attributes is optional here, as long as we identify the correct device.

Identification is possible using `idProduct` and `idVendor`, nevertheless `nitropy start update` and `nitropy start set-identity` is not working. Next step here is to dig into the errors that appear there...

> 3. Here is how hidapi has it's implementation for USB communication for reference: https://github.com/libusb/hidapi/blob/master/windows/hid.c

yes, also on the list: find out if I can low-level-communicate with the device using its handle and `.write()` + `.read()`

> 4. Can we compare our implementation/distribution with some other Python applications which use libusb under Windows?

sure do, but I was under the impression this was working in windows before (but maybe I am wrong, and it never worked?) `libusb-win32` has some `filter` wizard to allow passing through specific usb-devices, let's see if this helps ...

**Comment by szszszsz** [comment]
> Generally: is there a GNUK device, which comes with windows support ? any hints?

None as far as I am concern,aside from Nitrokey Start support being WIP. I was as well thinking this works out of the box with Pip sourced installation. See original scripts for testing with older update tool version: https://github.com/Nitrokey/nitrokey-start-firmware/tree/gnuk1.2-regnual-fix/tool.

Another thing is, that Windows 10 is making rolling releases all the time, and this stopping to work might have been oversighted.

**Comment by jans23** [comment]
I'm wondering if this issue occurs in a similar way for other tools which use libusb or hidapi?

**Comment by szszszsz** [comment]
@daringer Regarding https://github.com/Nitrokey/pynitrokey/issues/27#issuecomment-716472359: could you elaborate on point 1 in your answer to keep track of it for the future?

**Comment by daringer** [comment]
> @daringer Regarding [#27 (comment)](https://github.com/Nitrokey/pynitrokey/issues/27#issuecomment-716472359): could you elaborate on point 1 in your answer to keep track of it for the future?

Mostly to avoid any issues I test inside an elevated shell (as Administrator), here I did exactly this. Nevertheless I (at this point) cannot judge whether one needs to run it as Administrator or not, because both options currently do not work.

**Comment by mcuee** [comment]
For Windows, you should really use latest pyusb release 1.1.0 (released on14 Sep 2020) which fixes many issues of 1.0.2 (released on 12 Oct 2017). The new developer Jonas is very responsive if you post your issues in pyusb github.

As for libusb, you can use latest 1.0.24 release.

PS: I am the "non-developer" admin of libusb and pyusb.

**Comment by mcuee** [comment]
BTW, if your device is HID device, actually libusb project will recommend you to use HIDAPI and HIDAPI has a python binding called cython-hidapi.

**Comment by szszszsz** [comment]
Hi @mcuee !
Nice to meet you and thank you for the tips! Updating libusb sounds interesting. We must have missed its release.
We need libusb for the firmware update of Nitrokey Start, so we cannot switch entirely to the HIDAPI, otherwise that would be a good idea of course.

@daringer Could you run a check with the updated libusb?

**Comment by Alexus9** [comment]
It’s cumbersome to start Linux when I would like to change the Nitrokey Start identity for Windows application. Is it possible to describe the manual steps to put in effect the libusb 1.0.24 to give it a try? 

Maybe starting like this: „Using Zadig, install WinUSB driver, update pyusb by this command: …“ etc. 

I made some attempts without any success. Above all I’m not sure how to install the libusb 1.0.24 DLL/Libs.

So I would not have to wait for the comfortable installation package.

**Comment by Alexus9** [comment]
I have found a solution that I can currently live with (Windows 10 Version 20H2, Build 19042.867):

By default, when Nitrokey Start has been inserted, in Windows Device Manager entries can be found for Smartcard Reader and Smartcard:

![eingesteckt_550x450](https://user-images.githubusercontent.com/48854625/113855619-8cef8100-97a0-11eb-8abb-0b405a58bb41.jpg)

`gpg --card-status` does work.

Install nitropy.

```
>nitropy version
*** ←[31;01mNitrokey tool for Nitrokey FIDO2 & Nitrokey Start←[39;49;00m
0.4.1
```
nitropy produces error message as expected:
```
>nitropy start list
*** ←[31;01mNitrokey tool for Nitrokey FIDO2 & Nitrokey Start←[39;49;00m
:: 'Nitrokey Start' keys:
Warning: no backend was found to use for communication. Please refer to documentation how to install additional libraries.
```


Download Zadig 2.5, install WinUSB driver for Nitrokey Start device:
![Zadig_454x200](https://user-images.githubusercontent.com/48854625/113856921-2703f900-97a2-11eb-8c22-0af00c150c26.jpg)

Now in Windows Device Manager the entries for Smartcard and Smartcard Reader have been disappeared, Nitrokey Start can be seen under USB Devices:

![nach Zadig_509x450](https://user-images.githubusercontent.com/48854625/113856108-1737e500-97a1-11eb-8583-c3d01ee1524f.jpg)


`gpg --card-status` doesn’t work any more:
```
>gpg --card-status
gpg: selecting card failed: No such device
gpg: OpenPGP Karte ist nicht vorhanden: No such device
```

Downloaded `libusb-1.0.24.7z`, copy `libusb-1.0.24.7z\VS2019\MS64\dll\libusb-1.0.dll` to a directory which is present in %PATH% variable. I copied it to `C:\Users\<username>\AppData\Local\Microsoft\WindowsApps` (probably not perfect place, but works for me)

nitropy does work now:
```
>nitropy ls
*** ←[31;01mNitrokey tool for Nitrokey FIDO2 & Nitrokey Start←[39;49;00m
:: 'Nitrokey FIDO2' keys
:: 'Nitrokey Start' keys:
FSIJ-1.2.15-43115322: Nitrokey Nitrokey Start (RTM.10)
```

`nitropy start set-identity` does work too, I can change the Nitrokey identity.

To work with gpg, reinstall original Windows driver:

In Windows Device Manager mark Nitrokey Start, choose Update Driver and reinstall WUDF driver from your computer. Then you have the driver situation of the beginning again.

When you try nitropy it doesn't work any more, as expected, but you don’t see the backend error message any more:

```
>nitropy start list
*** ←[31;01mNitrokey tool for Nitrokey FIDO2 & Nitrokey Start←[39;49;00m
:: 'Nitrokey Start' keys:
None: None None (None)
```

That is caused by the presence of `libusb-1.0.dll` in path IMO.

To change the Nitrokey identity again you can go into Windows Device Manager again and update the WUDF driver by the Nitrokey Start driver from your computer. Then nitropy works again.

**Comment by Alexus9** [comment]
@Daringer I’m not sure about the next steps. I’ve seen v0.4.2.nitrokey, but it's just the source, no Windows executables. I don’t know how to run `nitropy` from source, if this is intended. The easiest way for me would be to use a msi installation file.

**Comment by daringer** [comment]
the recent release `0.4.3.1` also consists of a windows binary and an msi-installer, also adapted your solution, could you retest please?

**Comment by Alexus9** [comment]
Basically the same as above (also with admin rights, tested with Windows 20H2 and 21H1).

The error message `no backend was found` doesn’t appear any more, but otherwise unfortunately, depending on installed driver, either `nitropy-0.4.3.1.exe` can access the Nitrokey Start or `gpg --card-status` works, not both. Summarizing:

Nitrokey Start inserted, 
when in Windows Device Manager entries can be found for Smartcard Reader (with device `Microsoft Usbccid-Smartcart-Reader (WUDF)`) and Smartcards:
```
>nitropy-0.4.3.1.exe start list
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start & NetHSM
:: 'Nitrokey Start' keys:
None: None None (None)
```

`gpg --card-status` works.

After having updated driver for `Microsoft Usbccid-Smartcart-Reader (WUDF)` under Smartcard Reader to driver for device `Nitrokey Start` (then in Windows Device Manager an entry Nitrokey Start exists under USB Devices):

```
>nitropy-0.4.3.1.exe start list
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start & NetHSM
:: 'Nitrokey Start' keys:
FSIJ-1.2.15-43115322: Nitrokey Nitrokey Start (RTM.10)

```
`gpg --card-status` doesn’t work:

```
>gpg --card-status
gpg: selecting card failed: No such device
gpg: OpenPGP Karte ist nicht vorhanden: No such device
Nitrokey Start inserted, can be seen under USB Devices:
```

**Comment by daringer** [comment]
closing - legacy nitrokey support is essentially deprecated in pynitrokey
