### ISSUE TITLE
Running fails in a python 3.10 venv

### ISSUE THREAD

**Issue by sdlarsen** [Nitrokey/pynitrokey#281]
Creating a venv with python3.10 -m venv and installing pynitrokey there works (it fails on my default 3.11)

Installed with `pip install pynitro`

When running, I get this:
`(pynitro) ╭─sdl@tux ~/projects/sdl/pynitro
╰─➤  pynitro
Traceback (most recent call last):
  File "/home/sdl/projects/sdl/venv/pynitro/bin/pynitro", line 5, in <module>
    from pynitro.main import app
  File "/home/sdl/projects/sdl/venv/pynitro/lib/python3.10/site-packages/pynitro/main.py", line 13, in <module>
    from infra_utils.pulumi_util import NitroPulumiInfra
ModuleNotFoundError: No module named 'infra_utils'`

Is that expected, or am I doing something wrong?

**Comment by sdlarsen** [comment]
Will remove this as install fails. Will create another issue on that.
