### ISSUE TITLE
fido2 reset failed

### ISSUE THREAD

**Issue by jans23** [Nitrokey/pynitrokey#52]
Using nitropy 0.4.0 with NK FIDO2 2.2.0:

<details>
<summary> click to show log </summary>

```
$ nitropy fido2 reset
*** Nitrokey tool for Nitrokey FIDO2 & Nitrokey Start
Warning: Your credentials will be lost!!! continue? [(y)es/(n)o]: y
choosing: yes
Press key to confirm -- again, your credentials will be lost!!!
Traceback (most recent call last):
  File "/home/jan/.local/bin/nitropy", line 8, in <module>
    sys.exit(nitropy())
  File "/home/jan/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jan/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jan/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jan/.local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jan/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jan/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jan/.local/lib/python3.8/site-packages/pynitrokey/cli/fido2.py", line 394, in reset
    nkfido2.find(serial).reset()
  File "/home/jan/.local/lib/python3.8/site-packages/pynitrokey/fido2/client.py", line 183, in reset
    self.ctap2.reset()
  File "/home/jan/.local/lib/python3.8/site-packages/fido2/ctap2.py", line 795, in reset
    self.send_cbor(CTAP2.CMD.RESET, event=event, on_keepalive=on_keepalive)
  File "/home/jan/.local/lib/python3.8/site-packages/fido2/ctap2.py", line 645, in send_cbor
    raise CtapError(status)
fido2.ctap.CtapError: CTAP error: 0x30 - NOT_ALLOWED

```

</details>

**Comment by szszszsz** [comment]
This is already fixed in v0.4.1 - log below. Please update with:
```
pip3 install -U pynitrokey --user
```
(or `sudo pip3` and without `--user` if installed system wide)

<details>
<summary> click to show </summary>

```
sz@stumpy ~> nitropy fido2 reset
*** Nitrokey tool for Nitrokey FIDO2 & Nitrokey Start
Reset is only possible 10secs after plugging in the device.
Please (re-)plug in your Nitrokey FIDO2 now!
Warning: Your credentials will be lost!!! continue? [(y)es/(n)o]: yes
Press key to confirm -- again, your credentials will be lost!!!
Critical error:
Reset failed (CTAP error: 0x30 - NOT_ALLOWED)
Did you confirm with a key-press 10secs after plugging in?
Please re-try...

--------------------------------------------------------------------------------
Critical error occurred, exiting now
Unexpected? Is this a bug? Do you would like to get support/help?
- You can report issues at: https://github.com/Nitrokey/pynitrokey/issues/
- Writing an e-mail to: support@nitrokey.com is also possible
- Please attach the log: '/tmp/nitropy.log.ihi13hjt' with any support/help request!
--------------------------------------------------------------------------------

```
</details>

Error message might be a little clearer though.

**Comment by szszszsz** [comment]
Closing as invalid, since its already fixed.

I think though that it would be nice to have here some update check, and/or command for the package updating (as written in the previous message). What do you think? @daringer @jans23 

- [ ] clearer error message for the FIDO2 reset failure
- [ ] update command as a hint in case of any errors, and before updating NK Start
- [ ] version check with the Github as well just in case
- [ ] print own version at the start; change welcome message

**Comment by jans23** [comment]
I like the suggestions above. Also:

* [ ] More clear wording, use consistent terminology. E.g. what is "key"? State "Nitrokey" where it is applicable.

**Comment by szszszsz** [comment]
Occurred again with Nitrokey 3 and version `0.4.9`.

**Comment by szszszsz** [comment]
False alarm - the message is shown, but guide what to do next runs away of the user's attention - to improve.

**Comment by szszszsz** [comment]
This one should be fixed already. Please reopen otherwise.
