### ISSUE TITLE
Warn about not supported dependencies

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#92]
Check the dependencies installed and warn, if they are not supported.
I have just installed pynitrokey, and it failed with the basic check (see below). 

Edit: I am assuming this error comes from the dependencies API change (might be wrong)

<details>
<summary> log </summary>

```
sz@stumpy ~ [1]> nitropy fido2 verify
Nitrokey tool for Nitrokey FIDO2, Nitrokey Start & NetHSM
please press the button on your Nitrokey key
Touch your authenticator to generate a credential...
f22e2a6a4e3d2e1138c3dfd5379ecfbf15111929f9b541eee267faf982b91e43bc0ddf987e376b32c9e9dbaad777bc1a61000b66f208d95905330cbcda12e691eac6210c0000
Traceback (most recent call last):
  File "/home/sz/.local/bin/nitropy", line 8, in <module>
    sys.exit(nitropy())
  File "/home/sz/.local/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/sz/.local/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/sz/.local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sz/.local/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sz/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sz/.local/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/sz/.local/lib/python3.9/site-packages/pynitrokey/cli/fido2.py", line 547, in verify
    dev_fingerprint = cert.fingerprint(hashes.SHA256())
AttributeError: 'bytes' object has no attribute 'fingerprint'

```

</details>

**Comment by robin-nitrokey** [comment]
This specific error has been fixed and the general issue should be solved by specifying the minimum required dependency versions as suggested in https://github.com/Nitrokey/pynitrokey/issues/160, so I think this can be closed.  Do you agree?

**Comment by szszszsz** [comment]
Indeed. Closing as done.
