### ISSUE TITLE
Limit libusb dependency

### ISSUE THREAD

**Issue by szszszsz** [Nitrokey/pynitrokey#95]
Limit importing of the libusb based package to only actual calls, or wrap it accordingly.
Latest release is not running on the limited CI systems because of the missing library being imported to the main work space.
```
Step 12/12 : RUN nitropy version && arm-none-eabi-gcc --version | head -1
 ---> Running in bfe19af974c1
Traceback (most recent call last):
  File "/usr/local/bin/nitropy", line 5, in <module>
    from pynitrokey.cli import nitropy
  File "/usr/local/lib/python3.8/dist-packages/pynitrokey/cli/__init__.py", line 18, in <module>
    from pynitrokey.cli.pro import pro
  File "/usr/local/lib/python3.8/dist-packages/pynitrokey/cli/pro.py", line 7, in <module>
    import nkdfu.dfu as dfu
  File "/usr/local/lib/python3.8/dist-packages/nkdfu/dfu.py", line 7, in <module>
    import libusb1
  File "/usr/local/lib/python3.8/dist-packages/libusb1.py", line 8, in <module>
    from usb1.libusb1 import *
  File "/usr/local/lib/python3.8/dist-packages/usb1/__init__.py", line 61, in <module>
    from . import libusb1
  File "/usr/local/lib/python3.8/dist-packages/usb1/libusb1.py", line 185, in <module>
    libusb = _loadLibrary()
  File "/usr/local/lib/python3.8/dist-packages/usb1/libusb1.py", line 157, in _loadLibrary
    return dll_loader(filename, use_errno=True, use_last_error=True)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libusb-1.0.so: cannot open shared object file: No such file or directory
```

**Comment by daringer** [comment]
fixed
